spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbmasteruser
    password: FZU!NQ_`;-_jR]59<ITFBi*&qDR{-=1X
    url: jdbc:mysql://ls-ad4f5046753c91b4d440d5b9052d906e2dd928d9.c9m86ykomt6j.ap-northeast-2.rds.amazonaws.com:3306/Test?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 10
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db;MODE=MYSQL
#    username: sa
#    password:
  h2:
    console:
      enabled: true
  jpa:
    #    database: mysql
    defer-datasource-initialization: true
    open-in-view: false # ???? ?? ??? ??? ????? ???? ??
    #    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none # create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
        default-batch-fetch-size: 500
  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 300MB

  #console log ??
  output:
    ansi:
      enabled: always
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true